server:
  port: 33402
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  freemarker:
    suffix: .html
    cache: false
  application:
    name: mail-project
  profiles:
    active: dev
